### ISSUE TITLE
Listen and Track Cloudtrail Events

### ISSUE THREAD

**Issue by baldawar** [aws-solutions/quota-monitor-for-aws#100]
**Is your feature request related to a problem? Please describe.**

No

**Describe the feature you'd like**

I'm principal engineer for EventBridge. Super cool usage, though in my experience polling can become wasteful if you aren't making resource updates often. 

I'd recommend perhaps also adding an option to listen to `API events via CloudTrail` events for create / delete activities tied to a service resource and then updating a new "quota tracker table". You can also perform a low-frequency polling  (say one a week) as means to catch any inconsistencies when events are delayed or not delivered (in extremely rare cases).  

This should help make the system overall robust but let customers with low number of resource updates to not worry about wasteful computations.

**Comment by baldawar** [comment]
I see this working in conjunction with the current solution but gives a means to save on computation where event-based approach exist today. As more tools (such as service quotas) support publishing events, users will have a natural migration path to more effecient approach.

**Comment by rakshb** [comment]
Thanks for the request. We have added this to out backlog but it is not planned for the immediate roadmap of the solution.
