### ISSUE TITLE
Supported quotas that could be monitored by this solution 

### ISSUE THREAD

**Issue by salander0411** [aws-solutions/quota-monitor-for-aws#122]
**What were you initially searching for in the docs?**
I saw this doc and would like to confirm, does it mean that  only the service quotas that has the cloudwatch alarm integration are supported via this solution?  do we have a list on this ?  Manual check is nearly impossible for so many products and quotas.
 https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/plan-your-deployment.html#quotas  

**Is this related to an existing part of the documentation? Please share a link**  
 https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/plan-your-deployment.html#quotas  

**Describe how we could make it clearer**
(if yes) only quotas that allow resource usage monitoring using Amazon CloudWatch are supported by this solution

**If you have a proposed update, please share it here**
I would very like to request a list of cloudwatch alarm integration

**Comment by salander0411** [comment]
In the meanwhile,  I notice that in quota-monitor-sq-spoke.template,   only 5 services are defined,  does it mean that only those 5 services are checked via service quota?   Thanks

            "check-item-detail": {
              "Service": [
                "monitoring",
                "dynamodb",
                "ec2",
                "ecr",
                "firehose"
              ]
            }

**Comment by ilyaro** [comment]
Hi @abe-aws 

Thanks for the answer.
When next versions planned to be released?
We are interested in Route53 service quotas alerts not sure if uses cloud watch will be they supported also?
Example record set quota for hosted zone

**Comment by abe-aws** [comment]
Thanks [ilyaro](https://github.com/ilyaro),
We are targeting a release within a month, but we don't commit externally to specific release dates.
I just checked that none of the quotas listed for Route53 support resource usage monitoring at this point. So the solution can't monitor them. But as soon as any of the quotas start supporting resource usage monitoring, they will be picked up by the solution.

**Comment by ilyaro** [comment]
Thanks!
