### ISSUE TITLE
SQS Queue (QMReporterQMReporterLambda) is flushed with messages

### ISSUE THREAD

**Issue by jurgen-kamp** [aws-solutions/quota-monitor-for-aws#146]
**Describe the bug**

The QMReporterQMReporterLambda is being flushed with messages as the lambda function can handle a maximum of 100 messages (10 MAX_MESSAGES x 10 MAX_LOOPS)

**Comment by abe-aws** [comment]
Thanks for reporting, we will put in a fix by exposing configuration parameters in the next release.

**Comment by jurgen-kamp** [comment]
Thank you for your response. I got an InvalidParameterValue error when changing the environment variable higher that 10.
Error: "InvalidParameterValue - Value 20 for parameter MaxNumberOfMessages is invalid. Reason: Must be between 1 and 10, if provided."

(I also changed the EventBridge Rule to 1 minute.)

**Comment by abe-aws** [comment]
Thanks for pointing that out, [Receive message is limited to the 10](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html). So you  can only increase the number of loops (MAX_LOOPS). We will include this in the documentation in the next release.

**Comment by jurgen-kamp** [comment]
Thank for this fix. Do you maybe know what the maximum value of MAX_LOOPS is?

**Comment by abe-aws** [comment]
There is no hard limit. But at some point, the lambda function will probably run out of memory. Then you can increase the memory allocation.

**Comment by abe-aws** [comment]
[Documentation](https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/troubleshooting.html) updated
