### ISSUE TITLE
Lambda runtimes will need to be updated as nodejs14.x is going to be deprecated (Phase1: Nov 15, 2023)

### ISSUE THREAD

**Issue by devvick** [aws-solutions/quota-monitor-for-aws#148]
As per the Lambda runtime deprecation schedule below Lambda runtimes will need to be updated.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

https://github.com/search?q=repo%3Aaws-solutions%2Fquota-monitor-for-aws%20nodejs14&type=code

AWS Trusted Advisor is already throwing out warnings on deployed Lambdas.

**Comment by abe-aws** [comment]
Thanks, we will update in the next release..

**Comment by abe-aws** [comment]
fixed in https://github.com/aws-solutions/quota-monitor-for-aws/releases/tag/v6.2.2
