### ISSUE TITLE
Make the Threshold for Sending Notifications Customizable

### ISSUE THREAD

**Issue by jlachenauer** [aws-solutions/quota-monitor-for-aws#151]
We would like to be able to customize the thresholds for sending notifications. This would mean being able to choose a warning threshold less than the quota limit such that if the utilization for a particular quota exceeded that warning value, a notification would be sent out.

For example, if our limit for RDS clusters is 100, we may want a warning notification sent out if we exceed 80 clusters.

Thank you!

**Comment by abe-aws** [comment]
This is already a template parameter in the spoke stack. In the [non-organization mode](https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/step-1.-choose-your-deployment-scenario.html) you can specify the [OK/WARN/ERROR threshold](https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/architecture-overview.html) when you are deploying the stack. The template parameter isn't exposed in the hub for org deployment, we will expose that parameter in the next release.

**Comment by abe-aws** [comment]
done in https://github.com/aws-solutions/quota-monitor-for-aws/releases/tag/v6.2.2
