### ISSUE TITLE
ListManager Lambda function exceeds ListServiceQuotas quota

### ISSUE THREAD

**Issue by anoryx** [aws-solutions/quota-monitor-for-aws#154]
**Describe the bug**

QMListManager Lambda function is exceeding the `ListServiceQuotas` API quota.

**To Reproduce**

1. Install [`quota-monitor-hub-no-ou.template`](https://solutions-reference.s3.amazonaws.com/quota-monitor-for-aws/latest/quota-monitor-hub-no-ou.template) in monitoring account.
2. Install [`quota-monitor-sq-spoke.template`](https://solutions-reference.s3.amazonaws.com/quota-monitor-for-aws/latest/quota-monitor-sq-spoke.template) in spoke accounts and regions.

**Expected behavior**

Quota List Manager Lambda runs without error.

**Please complete the following information about the solution:**

- [ ] Version: 6.2.1
- [ ] Region: eu-central-1
- [ ] Was the solution modified from the version published on this repository? No.
- [ ] If the answer to the previous question was yes, are the changes available on GitHub? N/A
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses? This error is the result of a service quota that cannot be adjusted (ListServiceQuotas, [10 per second per region](https://docs.aws.amazon.com/general/latest/gr/servicequotas.html#limits_servicequotas))
- [ ] Were there any errors in the CloudWatch Logs? [How to enable debug mode?](https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/troubleshooting.html) Yes:

```
{
  "errorType": "TooManyRequestsException",
  "errorMessage": "The request failed because you exceeded the rate quota for this operation.",
  "name": "TooManyRequestsException",
  "$fault": "client",
  "$metadata": {
    "httpStatusCode": 400,
    "requestId": "f0a440fa-57e8-49d6-9d85-a15d7ad56e81",
    "attempts": 4,
    "totalRetryDelay": 2118
  },
  "__type": "TooManyRequestsException",
  "stack": [
    "TooManyRequestsException: The request failed because you exceeded the rate quota for this operation.",
    "    at de_TooManyRequestsExceptionRes (/opt/nodejs/node_modules/@aws-sdk/client-service-quotas/dist-cjs/protocols/Aws_json1_1.js:1239:23)",
    "    at de_ListServiceQuotasCommandError (/opt/nodejs/node_modules/@aws-sdk/client-service-quotas/dist-cjs/protocols/Aws_json1_1.js:788:25)",
    "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "    at async /opt/nodejs/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24",
    "    at async /opt/nodejs/node_modules/@aws-sdk/middleware-signing/dist-cjs/awsAuthMiddleware.js:14:20",
    "    at async /opt/nodejs/node_modules/@aws-sdk/middleware-retry/dist-cjs/retryMiddleware.js:27:46",
    "    at async /opt/nodejs/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26",
    "    at async makePagedClientRequest (/opt/nodejs/node_modules/@aws-sdk/client-service-quotas/dist-cjs/pagination/ListServiceQuotasPaginator.js:7:12)",
    "    at async paginateListServiceQuotas (/opt/nodejs/node_modules/@aws-sdk/client-service-quotas/dist-cjs/pagination/ListServiceQuotasPaginator.js:17:20)",
    "    at async ServiceQuotasHelper.getQuotaList (/opt/nodejs/node_modules/solutions-utils/lib/servicequotas.js:54:26)"
  ]
}
```

**Comment by abe-aws** [comment]
Thanks for reporting this. Yes, this can happen, but the lambda function is retried 3 times and we have observed that the quotas will be saved to the dynamo db table at the end of the process. If you have observed that the subsequent retries also failed, you can manually re-run the lambda function with the following test event (It normally runs every month to refresh the list of supported quotas)

```
{
	"detail-type":"Scheduled Event",
	"Details":"simulated event bridge event"
}
```

**Comment by anoryx** [comment]
Thanks for the response. I don't love that I have to expect errors with this Lambda function, as they might obscure other real and relevant errors, but I accept that there may not be a viable workaround given the ListServiceQuotas API limit immutability.

**Comment by abe-aws** [comment]
I hear you. We will work on improving the logging and outputting this - say as a warning.
