### ISSUE TITLE
Notification Quota IDs

### ISSUE THREAD

**Issue by andynicklen** [aws-solutions/quota-monitor-for-aws#156]
**What were you initially searching for in the docs?**
Notification instructions

**Is this related to an existing part of the documentation? Please share a link**
[notification instructions](https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/step-6.-configure-notifications-optional.html), i.e. muting specific checks.

**Describe how we could make it clearer**
Ideally provide more detailed examples of where to find the IDs required, perhaps some links to aws documentation or pointers on how to find them, such as within Service Quotas in the AWS portal. Do [these](https://docs.aws.amazon.com/awssupport/latest/user/service-limits.html#ec2-vpc-elastic-ip-address) quota id's apply (i've tested one and it didnt mute the notification).

In addition, presumaly the changes in the notification SSM parameter can be made retrospectively (after the hub and spoke have been deployed). If so, are you picked up automatically or is there manual process to activate them?

**If you have a proposed update, please share it here**
More detailed notification instructions and examples/links

**Comment by abe-aws** [comment]
Thanks for the feedback. We will provide more examples in the documentation in the next release.

The notification filtering works with a string / pattern match. You can start from what is sent via email / slack message. Look for the keys Service, LimitName for notifications from Trusted Advisor. And for the notifications for Server Quotas, look for the entries for Service, Limit Name, Resource, Limit Code. Then, you can apply the pattern ServiceCode[:QuotaCode|QuotaName|Resource|LimitName].

Correct, there is no manual process to activate the change of the notification filters in the SSM parameter. The changes are picked up automatically.

**Comment by andynicklen** [comment]
Hi @abe-aws - that note about looking for the Service and LimitName in the email worked a treat thanks. Perhaps i should have worked that out myself but no harm extending the documentation slightly to include that tip. Many thanks
