### ISSUE TITLE
[putItem] unexpected error: TypeError: Cannot read properties of undefined (reading 'S')

### ISSUE THREAD

**Issue by KadalurSupreeth** [aws-solutions/quota-monitor-for-aws#172]
upgraded from version 6.2.2 to recent one 6.2.3

I see below error in the hub report lambda function while inserting usage data into Hub dynamoDB table. This is happening only for source coming from Trust Advisor. It is able to insert values coming from source service quotas. 

Error:
[WARN] [putItem] unexpected error: TypeError: Cannot read properties of undefined (reading 'S')

Please verify at the earliest. Thanks

**Comment by abe-aws** [comment]
Thanks for reporting, looking into it.

**Comment by abe-aws** [comment]
We will include the fix in the next release.

**Comment by KadalurSupreeth** [comment]
@abe-aws  - I had to upgrade from version 6.2.2 to the recent one 6.2.3 because there was a vulnerability issue in 6.2.2 as mentioned in the change logs in this repo.

Is there a work around in the CloudFormation templates which I can change as a work around to fix this problem?  Need this ASAP. Thanks

**Comment by KadalurSupreeth** [comment]
@abe-aws  - I had to upgrade from version 6.2.2 to the recent one 6.2.3 because there was a vulnerability issue in 6.2.2 as mentioned in the change logs in this repo.

Is there a work around in the CloudFormation templates which I can change as a around until this fix comes in next release? Need this ASAP. Thanks

**Comment by abe-aws** [comment]
6.2.3 is to address [this](https://github.com/advisories/GHSA-67hx-6x53-jw92). That is a dev dependency used only when you run tests (npm test). So you can deploy / continue using 6.2.2 without any impact.

**Comment by abe-aws** [comment]
Fixed in release [v6.2.4](https://github.com/aws-solutions/quota-monitor-for-aws/releases/tag/v6.2.4)
