### ISSUE TITLE
[Question] Is there a list of service Quotas whoes usage is been tracked by this solution ? 

### ISSUE THREAD

**Issue by Shubzshah** [aws-solutions/quota-monitor-for-aws#176]
Hello Team,

I am looking to check the usage metrics against very specific quotas and wanted to know if this solution supports it. 
Is there a list that I can refer to for understanding which service quotas can be tracked using this solution ? 

The Quota codes for which I am looking for a solution is 

The 3 main ones : 

Subnets that can be shared with an account - L-44499CD2
Resource shares - L-595828F9
SG per network interface - L-2AFB9258

Other quotas that are to be tracked : 

VPC per region - L-F678F1CE
SG inbound/outbound - L-0EA8095F 
ASG quotas - Both quotas
NLBs per region - L-69A177A2
ALB per region - L-53DA6B97
EC2 vCPU
Subnets per VPC - L-407747CB

Thanks

**Comment by abe-aws** [comment]
Yes, you can list the list of available quotas for service with `aws service-quotas list-service-quotas --service-code <SERVICE_CODE>`, where SERVICE_CODE can be say ec2, vpc or any other service. But only those quotas which have a node `UsageMetric.MetricNamespace = AWS/Usage` can be monitored. You can for example use jq to get the list of supported quotas in one go `aws service-quotas list-service-quotas --service-code ec2 | jq '.Quotas | .[] | select(.UsageMetric.MetricNamespace=="AWS/Usage")'`
