### ISSUE TITLE
Support for Israel(Tel Aviv) Region "il-central-1"

### ISSUE THREAD

**Issue by veltz-avi** [aws-solutions/quota-monitor-for-aws#177]
The solution deployment is failing in Israel(Tel Aviv) Region "il-central-1"
Version:  v6.2.4
Released: 11/2023

**Additional context**
`Error occurred while GetObject. S3 Error Code: IllegalLocationConstraintException. S3 Error Message: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException;`

![Screenshot 2023-12-19 at 00 49 44](https://github.com/aws-solutions/quota-monitor-for-aws/assets/68636084/5bc3faa7-667b-4592-aa92-43fe3f6340ac)

**Comment by morjoan** [comment]
Thanks for this request. We will add support for this region in a future release.

**Comment by morjoan** [comment]
This has been added to our backlog for tracking.

**Comment by sanjay-reddy-kandi** [comment]
Fixed in `v6.3.0`. Closing issue.
