### ISSUE TITLE
Fix for expiration of records in DynamoDB not found in 6.2.5

### ISSUE THREAD

**Issue by klaffka** [aws-solutions/quota-monitor-for-aws#183]
Hello,
according to the current release notes, the problem with the incorrect entries for expiring entries should be fixed in the current release. But I couldn't find the [fix](https://github.com/aws-solutions/quota-monitor-for-aws/blob/d736c5a7241d9b9c14eb88e91bff2a0276167731/source/lambda/services/reporter/lib/limit-report.ts#L83) from the pull request [#47](https://github.com/aws-solutions/quota-monitor-for-aws/pull/47) is that correct?

**Comment by abe-aws** [comment]
That's correct - this was missed. Thanks for catching that. It will be included in the next release.

**Comment by G-Lenz** [comment]
This should be fixed in v6.2.6
