### ISSUE TITLE
Getting error %%SOLUTION_NAME%%' is not a valid value for TagValue

### ISSUE THREAD

**Issue by mguja-fcc** [aws-solutions/quota-monitor-for-aws#186]
**Describe the bug**
Solution version v6.2.5

getting error when running command: npm run orgHub:deploy -- deploy quota-monitor-hub

CREATE_FAILED        | AWS::ServiceCatalogAppRegistry::AttributeGroup            | HubAppRegistryAppl...ibuteGroup9173E29C
Resource handler returned message: "'%%SOLUTION_NAME%%' is not a valid value for TagValue - it contains illegal characters (Service: ServiceCatalogAppRegistry, Status Code: 400

**To Reproduce**
run npm run orgHub:deploy -- deploy quota-monitor-hub

**Expected behavior**
solution deployed

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v6.2.5]

**Comment by shujacks** [comment]
Thanks for reaching out. Let us know if you still have any question on this.
