### ISSUE TITLE
Events are not being deposited to custom EventBus QuotaMonitorBus from spoke accounts

### ISSUE THREAD

**Issue by mguja-fcc** [aws-solutions/quota-monitor-for-aws#188]
**Describe the bug**

Events are not being deposited to custom EventBus QuotaMonitorBus from spoke accounts. 

**To Reproduce**

1. Deploy solution
2. Have at least a warning item in Trusted Advisor
3. Invoke Trusted advisor refresh
4. There is invocation error for StackSet-QM-TA-Spoke-StackSet-3e-TAWarnRule* rule. 

Assuming same issue is for the QuotaMonitorSpokeBus

**Expected behavior**

Warning is sent to SNS topic.

**Please complete the following information about the solution:**
- [ ] Version: [v6.2.5]
Temporary fix: had to add scoped down policy to the custom bus QuotaMonitorBus to allow events:PutEvents . Notifications started to come in.

**Comment by mguja-fcc** [comment]
Any update on this ? we want to deploy though code without a need of manual steps. Thanks.

**Comment by francotel** [comment]
In my case have this error from lambda spoke (target account):
[WARN] [getMetricData] ValidationError - The values for parameter id in MetricDataQueries are not unique.
[WARN] [getMetricData] ValidationError - Maximum number of SERVICE_QUOTA functions (100) exceeded

**Comment by G-Lenz** [comment]
Those errors are a separate issue which we are currently looking into, if you'd like you can open a separate issue for tracking purposes which we can also use to provide any updates on that particular error.
