### ISSUE TITLE
List of services that supports Aws services by using this Service Quota Design solution

### ISSUE THREAD

**Issue by conpsudd** [aws-solutions/quota-monitor-for-aws#191]
Previous version when we used v5.3.5 of Quota Monitor supports only 5 services from Service Quotas (EC2, monitoring, dynamodb, ECR and firehose). 

https://github.com/aws-solutions/quota-monitor-for-aws/releases - 6.2.6 - Please list down the services that supports using this Service Quota design solution.

**Comment by G-Lenz** [comment]
Hi,
As of version 6.1, the solution has support for monitoring all usage reporting quotas from all services supported by Service Quotas.
