### ISSUE TITLE
Latest Template Not Deployed from AWS Solutions Page

### ISSUE THREAD

**Issue by adrian-is-on-github** [aws-solutions/quota-monitor-for-aws#192]
**Describe the bug**

Deploying deprecated runtime versions - results in deployment failure. Listed as the latest on the AWS Solutions Page for quota monitor 

**To Reproduce**

Deploy latest release stack from this page: https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/update-the-solution.html

Link: https://solutions-reference.s3.amazonaws.com/limit-monitor/latest/limit-monitor.template

**Expected behavior**

Deployment not to use node 12.x runtimes for any lambdas

**Please complete the following information about the solution:**

-   "Description": "(SO0005) - limit-monitor, version v5.3.5" (looks like a wee bit older than the expected version)

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SOXXXX) - The AWS CloudFormation template for deployment of the AWS Solution. Version **vx.y.z**_". You can also find the version from [releases](https://github.com/aws-solutions/quota-monitor-for-aws/releases)

- [us-east-1] Region: 
- [ no ] Was the solution modified from the version published on this repository?
- [x] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the services this solution uses?
- [n/a] Were there any errors in the CloudWatch Logs? [How to enable debug mode?](https://docs.aws.amazon.com/solutions/latest/quota-monitor-for-aws/troubleshooting.html)

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).

**Additional context**

**Comment by G-Lenz** [comment]
Thank you for making us aware of this issue. We will fix the documentation. In the mean time you can use the other links to update the solution templates, such as the links in the `Deploy the Solution` section or from the `Cloudformation Templates` link on the landing page.

**Comment by G-Lenz** [comment]
Hi @adrian-is-on-github 
The IG has been updated, those links now reference the templates section of the doc which contain the correct templates.
