### ISSUE TITLE
Allow concurrent deployment in same region for QM-SQ-Spoke-StackSet

### ISSUE THREAD

**Issue by ddemaret-plaid** [aws-solutions/quota-monitor-for-aws#204]
**Is your feature request related to a problem? Please describe.**

This feature might not be possible based on cloud formation limitations so forgive me if I'm wrong! I see that there's a couple options during deploying that we can set concurrency per region. However all my accounts are currently in 1 region (about 15 accounts). Because of this the update from 1 version to another happens sequentially and for the latest release this was > 30 mins. This is for the QM-SQ-Spoke-StackSet. 

```
│ Error: waiting for CloudFormation Stack (quota-monitor-hub) update: timeout while waiting for state to become 'CREATE_COMPLETE, UPDATE_COMPLETE, UPDATE_ROLLBACK_COMPLETE, UPDATE_ROLLBACK_FAILED' (last state: 'UPDATE_IN_PROGRESS', timeout: 30m0s)
```

**Describe the feature you'd like**

Allow the update of the accounts to happen concurrently in the same region.

**Additional context**

**Comment by sanjay-reddy-kandi** [comment]
What values did you use the for the `RegionConcurrency` and `Percentage Maximum concurrent accounts` in the cfn template?

**Comment by ddemaret-plaid** [comment]
> What values did you use the for the `RegionConcurrency` and `Percentage Maximum concurrent accounts` in the cfn template?

```
    RegionConcurrency          = "PARALLEL"
    MaxConcurrentPercentage    = "100"
```
But all my accounts are in 1 region so I don't think that does anything?

**Comment by sanjay-reddy-kandi** [comment]
Based on this [AWS documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_StackSetOperationPreferences.html#API_StackSetOperationPreferences_Contents), `MaxConcurrentPercentage` is supposed to set the maximum number of accounts in which to perform this operation at one time. But I expect you are using the `FailureTolerancePercentage` default of zero, thereby if the operation is stopped in a Region, CloudFormation doesn't attempt the operation in any subsequent Regions, which essentially makes the process sequential. So You need to increase the `FailureTolerancePercentage` to make it more parallel.

**Comment by ddemaret-plaid** [comment]
Perfect thanks @sanjay-reddy-kandi
