### ISSUE TITLE
Timeout from limitCheckStack-LimitMonitorFunction every once in a while

### ISSUE THREAD

**Issue by omry-hay** [aws-solutions/quota-monitor-for-aws#60]
It seems that every once in a while (happens ~2 per day) we are getting a timeout from the Lambda. 
Looking at the cloudwatch logs there's nothing there.
In addition I see that this function consumes ~100-120MB of RAM and the limit of that function is 128MB.

I've added the graphs of the invocation and timeout, and the cloudwatch logs of a timed out invocation: 

![image](https://user-images.githubusercontent.com/46656490/98801178-209f6a00-241a-11eb-8cc0-28be45cea666.png)

![image](https://user-images.githubusercontent.com/46656490/98802234-a5d74e80-241b-11eb-8a85-1b3a8c2492ea.png)

This is  running the latest version of your code, deployed through the link in the [AWS Limit Monitor home page](https://aws.amazon.com/solutions/implementations/limit-monitor/) without any modifications.

**Comment by deolank** [comment]
Thanks for your feedback. We have added this bug to our backlog. As a workaround, please increase the lambda timeout to 900 seconds.

**Comment by omryhay1** [comment]
Hi @deolank - Thanks for your answer. 
There are other Lambda's that already have a timeout of 300 seconds and still gets a timeout, so I don't think increasing it to 900 will work, as there is probably something that is left hanging there 🤷‍♂️

**Comment by gsingh04** [comment]
updated in `v6.0.0`
