### ISSUE TITLE
README.md couple of improvements

### ISSUE THREAD

**Issue by kmturley** [aws-solutions/quota-monitor-for-aws#63]
There seems to be a missing command and some other improvements which could be made to improve the README.md file for new developers.

**1) Remove newline characters**

newline characters are not needed in bash:
```
cd ./deployment
chmod +x ./run-unit-tests.sh  \n
./run-unit-tests.sh \n
```
Should either be removed:
```
cd ./deployment
chmod +x ./run-unit-tests.sh
./run-unit-tests.sh
```
Or if intending to be a single multiline command:
```
cd ./deployment && \
  chmod +x ./run-unit-tests.sh && \
  ./run-unit-tests.sh
```

**2) Include missing command**

It is not clear which dist folder this refers to:
```
aws s3 cp ./dist/ s3://my-bucket-name/limit-monitor/latest/ --recursive --exclude "*" --include "*.template" --acl bucket-owner-full-control --profile aws-cred-profile-name
```
Would be better to include the cd command to make it clear:
```
cd ../source/lambda/services/limitreport
aws s3 cp ./dist/ s3://my-bucket-name/limit-monitor/latest/ --recursive --exclude "*" --include "*.template" --acl bucket-owner-full-control --profile aws-cred-profile-name
```
Or if we can pass through relative paths this would be clearer:
```
aws s3 cp ../source/lambda/services/limitreport/dist/ s3://my-bucket-name/limit-monitor/latest/ --recursive --exclude "*" --include "*.template" --acl bucket-owner-full-control --profile aws-cred-profile-name
```

**Comment by cchanley2003** [comment]
Even more confusing my assets were built into global-s3-assets for templates and regional-s3-assets for the lambda zips. So not sure why ./dist is mentioned at all. It seems like the command would be: 
`aws s3 cp ./global-s3-assets/ s3://my-bucket-name/limit-monitor/latest/ --recursive --exclude "*" --include "*.template" --acl bucket-owner-full-control --profile aws-cred-profile-name`

**Comment by Thrinadh-Kumpatla** [comment]
@cchanley2003 Yea make sense. The path they mention is for Dist folders and I'm not sure if it's required. Someone please clarify @kmturley

**Comment by gsingh04** [comment]
updated in `v6.0.0`
