### ISSUE TITLE
Wrong Condition for TASNSRule resource in limit-monitor.template

### ISSUE THREAD

**Issue by davcen** [aws-solutions/quota-monitor-for-aws#65]
Using the latest version of your template (5.3.3 at the time of writing) i've found a wrong "Condition" for the "TASNSRule" Resource (row 2145 in limit-monitor.template)

It's:
'Condition': 'SlackTrue'

It would be:
'Condition', 'SNSTrue'

If i don't set the Slack-related parameters (that was my use case) the EventBridge Rule for SNS will not be created.

**Comment by gsingh04** [comment]
addressed in `v6.0.0`
