### ISSUE TITLE
Add Auto Scaling Plans to the List of Services You Monitor

### ISSUE THREAD

**Issue by nicholas2345** [aws-solutions/quota-monitor-for-aws#68]

**Comment by rakshb** [comment]
Hello @nicholas2345 Thanks for submitting the request. We've added this to the backlog and will review it in a future release

**Comment by abe-aws** [comment]
Thanks the team is working on [this](https://github.com/aws-solutions/quota-monitor-for-aws/issues/122#issuecomment-1472229939)
