### ISSUE TITLE
Add Cloud Watch Alarms to the List of Services You Monitor

### ISSUE THREAD

**Issue by nicholas2345** [aws-solutions/quota-monitor-for-aws#69]

**Comment by rakshb** [comment]
Hello @nicholas2345 Thanks for submitting the request. We've added this to the backlog and will review it in a future release

**Comment by michaelinthecloud** [comment]
@nicholas2345 thank you for submitting this request, could you help us understand the ask better by sharing 1/ context on the problem you're running into while using Limit Monitor and 2/ if you're using Limit Monitor on behalf of a project/company, can you please share their name and use case?

**Comment by abe-aws** [comment]
The team is working on [this](https://github.com/aws-solutions/quota-monitor-for-aws/issues/122#issuecomment-1472229939)
