### ISSUE TITLE
EBS limit monitoring

### ISSUE THREAD

**Issue by nitrocode** [aws-solutions/quota-monitor-for-aws#70]
> You have exceeded your maximum gp2 storage limit of 600 TiB in this region. Please contact AWS Support to request an Elastic Block Store service limit increase.

It would be nice to get messages when approaching our EBS limits like we do with other EC2 limits

**Comment by gsingh04** [comment]
Thanks for reaching out to us, 

We have added this to the backlog items. We will consider this in future releases.

**Comment by nitrocode** [comment]
That's good to hear. Id like to contribute this change. Could you point me in the right direction on how best to approach this?

**Comment by rakshb** [comment]
@nitrocode You can send a PR to us on this GitHub repo. We will review it when we make this change. thanks for your contribution

**Comment by gsingh04** [comment]
Please review instructions [here](https://github.com/aws-solutions/quota-monitor-for-aws#customization) for solution customizations. You can submit a [PR](https://github.com/aws-solutions/quota-monitor-for-aws/blob/main/.github/PULL_REQUEST_TEMPLATE.md) for us to review the changes.

**Comment by nitrocode** [comment]
@gsingh04 Was this closed because it's now implemented?
