### ISSUE TITLE
Enable support for StackSet SERVICE_MANAGED

### ISSUE THREAD

**Issue by pproux** [aws-solutions/quota-monitor-for-aws#71]
A great feature would be to have a support for StackSet SERVICE_MANAGED using Organization OU. 

Currently if i want to deploy spoke stacks through Stackset on a Organization OU, i still need to add the new account into the "Account list" master stack parameter.

Additionnaly, nested stacks are not supported in stackset SERVICE_MANAGED permission model.

**Comment by gsingh04** [comment]
@pproux thanks for your request. 

You are right, StackSet deployment would certainly make it easy to deploy spoke templates in Organization member accounts. Also, nested stacks as you pointed out, is not supported with SERVICE_MANAGED permission model.

We have added your request to our backlog. We will try to work with the limitations and add support for StackSet deployments in the next release of the solution.

**Comment by dlutsch** [comment]
@gsingh04 Any news on this feature?

**Comment by gsingh04** [comment]
updated in `v6.0.0`
