### ISSUE TITLE
Organization-wide monitoring

### ISSUE THREAD

**Issue by RobBrazier** [aws-solutions/quota-monitor-for-aws#76]
Hi,

We were hoping to apply this in our production environment, however the organization has nearly 1000 accounts and is constantly changing, so would be very difficult to keep the AccountList parameter in the hub template up-to-date after every account vend / suspension / removal

Would it be possible to specify a set of organization units (or an entire organization) to allow us to monitor the entire estate?

Worth noting as well that we would likely be deploying the products via [aws-service-catalog-puppet ](https://github.com/awslabs/aws-service-catalog-puppet)

I see it's used in the event rules, CrossAccntTrust and AnonymousData custom resources

**Comment by gsingh04** [comment]
Hello @RobBrazier 

Thanks for opening the issue.

We are aware of this limitation and already have the item on our backlog. In the meanwhile, please refer to https://github.com/awslabs/aws-limit-monitor/issues/44
to overcome this limitation at your end.

**Comment by gsingh04** [comment]
updated in `v6.0.0`
