### ISSUE TITLE
Reference error when using template with empty SNSEvents

### ISSUE THREAD

**Issue by arnaudmm** [aws-solutions/quota-monitor-for-aws#80]
Hello !

Using this template : https://s3.amazonaws.com/solutions-reference/limit-monitor/latest/limit-monitor.template (version 5.3.4)

With empty parameter : SNSEmail and SNSEvents 

Results in a reference error because some resources : "TASNSRule" and "SNSTopicPolicyE1168CD7" do not have the "Condition": "SNSTrue"

Those resources should not be created if SNSEvents parameters are empty because SNSTopic is not created.

**Comment by gsingh04** [comment]
Thank you for raising this issue. 

This has been added to our backlog items. We will address this with next release.

**Comment by gsingh04** [comment]
resolved in `v6.0.0`
