### ISSUE TITLE
Transition to CDK v2

### ISSUE THREAD

**Issue by njbraun** [aws-solutions/quota-monitor-for-aws#87]
CDK v1 has now officially entered maintenance mode on June 1, 2022.  This library uses v1.  Are there plans to migrated to v2?

See: https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html

**Comment by gsingh04** [comment]
@njbraun  yes, we are working on the next release scheduled for Q3. The release will be using AWS CDK v2 and AWS SDK for JavaScript v3.

**Comment by gsingh04** [comment]
updated in `v6.0.0`
