### ISSUE TITLE
Support Deployment aws-limit-monitor on any other region(ex:ap-south-1) not on us-east-1

### ISSUE THREAD

**Issue by satya-narayan87** [aws-solutions/quota-monitor-for-aws#89]
As per [documentation ](https://aws.amazon.com/solutions/implementations/limit-monitor/) ,this solution is needed to be deployed on us-east-1, but in some case some accounts are not onboarded with the specific region, so have to go with other region. So for that case, what would be work around , please suggest!!

**Comment by gsingh04** [comment]
Currently, the way solution works is, it needs to refresh Trusted Advisor service limit checks. Trusted Advisor only supports us-east-1 as its data plane, reference [here](https://docs.aws.amazon.com/awssupport/latest/user/Welcome.html)

_"You can use the following endpoint to access the AWS Support API:
https://support.us-east-1.amazonaws.com/"_

This is the reason we recommend deploying in us-east-1. One way to overcome this would be to update this [line of code](https://github.com/aws-solutions/aws-limit-monitor/blob/master/source/lambda/services/tarefresh/lib/ta-refresh.js#L103) as
`new AWS.Support({region: 'us-east-1'}) // hard reference to us-east-1 for AWS Support endpoint`

We are working on releasing the next major version v6.0.0 of the solution in August and this design is going to continue to be the same where microservices using Trusted Advisor and Support APIs will only support us-east-1 deployment as we want to avoid cross region API calls by default.

**Comment by gsingh04** [comment]
updated in `v6.0.0`
