### ISSUE TITLE
Lambda runtimes will need to be updated as nodejs12.x is going to be deprecated (Phase1: Nov 14, 2022) (Phase2:Dec 14, 2022) 

### ISSUE THREAD

**Issue by vsr2158** [aws-solutions/quota-monitor-for-aws#92]
As per the Lambda runtime deprecation schedule below Lambda runtime will need to be updated.

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy

https://github.com/aws-solutions/aws-limit-monitor/blob/master/source/lib/limit-monitor-spoke-stack.ts

**Comment by gsingh04** [comment]
updated in `v6.0.0`
